### ISSUE TITLE
1Password Transparency

### ISSUE THREAD

**Issue by jgallias** [brianlovin/security-checklist#134]
Use a password manager: 1Password
"Sign up with Security Checklist to get 3 months free"
https://start.1password.com/sign-up/family?c=SECURELIST-FJN7FIKQ

How is this being offered?
What does Security Checklist get for offering this, if anything?
SECURELIST-FJN7FIKQ appears to be a referral/affiliate link code?

Thanks.

**Comment by brianlovin** [comment]
Security Checklist gets nothing. They offered a paid sponsorship but that didn't feel like the right decision for me to make.

So yeah, it's literally just 3 free months. It's a pure benefit to visitors. I'd be happy if other resources wanted to also offer discounts to help people improve their online privacy and security.
