### ISSUE TITLE
A Todoist template for the security checklist

### ISSUE THREAD

**Issue by hfauq** [brianlovin/security-checklist#139]
Hi @brianlovin 👋

When you launched the project, we briefly [talked](https://twitter.com/hfauq/status/1084887989598076928 ) about creating a Todoist template to make the security checklist actionable for the many Todoist users

I've just soft published it [here](https://todoist.com/templates/personal/internet-privacy-security). I added you as the author, and "Credits to securitycheckli.st ->" as a task in the project template. 

I'd love to know if you're cool with this as a template, you as the author, etc 👍

**Comment by brianlovin** [comment]
@hfauq this is awesome, works for me! Thanks for putting that together 👍
