### ISSUE TITLE
Incorrect link for "What is a VPN and why you need one"

### ISSUE THREAD

**Issue by rgjamkhedkar** [brianlovin/security-checklist#204]
The second link in the resources section of "Use a VPN" card goes to "https://www.theverge.com/2018/4/1/17185732/cloudflare-dns-service-1-1-1-1". Not sure where it should go instead. Found following articles with that title.
- https://www.pcmag.com/article/352757/you-need-a-vpn-and-heres-why
- https://lifehacker.com/why-you-should-be-using-a-vpn-and-how-to-choose-one-5940565

**Comment by brianlovin** [comment]
Hm, good call - I think either of those alternate links could work, mind opening a PR?

**Comment by rgjamkhedkar** [comment]
Sure I will do that.
