### ISSUE TITLE
Add section to turn off frequent locations for iOS

### ISSUE THREAD

**Issue by dmleong** [brianlovin/security-checklist#27]
Another privacy item that might be useful is [turning off frequently visited locations on iOS](https://www.imore.com/stop-iphone-tracking-frequent-locations) 

Would a section on reviewing the different ways that a phone is tracking you (by sending aggregate data to developers) be a useful section as well? 🤔

**Comment by brianlovin** [comment]
This is great, but perhaps makes sense in the "Review app permissions on your devices" section, what do you think? Or maybe we rename that section to "Review location, camera, and other sensitive device permissions" and then include this resource.

**Comment by brianlovin** [comment]
:shipit:
