### ISSUE TITLE
Do not use same Password Manager for Passwords and 2FA Codes

### ISSUE THREAD

**Issue by caloon** [brianlovin/security-checklist#36]
The website should mention that you shouldn't use a password manager for both, passwords and 2FA codes. 
Reason: this makes the password manager (which usually is locked with just one password) the single point of failure. 2FA actually becomes 1FA then, as the password manager is the only factor used for authentication.

**Comment by felixfoertsch** [comment]
#37

**Comment by brianlovin** [comment]
Done in #38 :)
