### ISSUE TITLE
Add Linux to the listed platforms

### ISSUE THREAD

**Issue by tchaffee** [brianlovin/security-checklist#40]
Linux is missing from the listed platforms. Considering that Linux is often used as a desktop in countries where people cannot afford Windows or macOS it would be a big help to global security if we can get Linux added to the list of platforms.

**Comment by yumyumbluesun** [comment]
Also Linux users may be more computer savvy and in positions that would help disseminate this to less-able co-workers who need it more.

**Comment by brianlovin** [comment]
Totally agree, perhaps it was a mistake to leave Linux off the v1. Going to see if I can get this up right now.
