### ISSUE TITLE
ProtonVPN Android link is not working. Update with replacement link: https://play.google.com/store/apps/details?id=ch.protonvpn.android

### ISSUE THREAD

**Issue by rob-patchett** [brianlovin/security-checklist#405]
Old link https://play.google.com/store/apps/details?id=com.protonvpn.android should be updated to https://play.google.com/store/apps/details?id=ch.protonvpn.android.

**Comment by brianlovin** [comment]
Thanks! Would you mind opening a PR for this?

**Comment by rob-patchett** [comment]
PR open 🙂
