### ISSUE TITLE
Add check for turn off geotagging

### ISSUE THREAD

**Issue by strayiker** [brianlovin/security-checklist#47]
> Your photos can tell everyone who’s watching them
>
> - where you live
> - where you spend your time
> - when there is noone home
> - where you park your car
> - and other information that you wouldn’t want to tell

[What is Geotag Security and How it Helps to Protect Your Family](https://www.geotag-security.com/)
[How to Avoid the Potential Risks of Geotagging](https://www.wikihow.com/Avoid-the-Potential-Risks-of-Geotagging)
[How to Turn OFF Geotagging For Photos On iPhone and iPad](https://www.techbout.com/turn-off-geotagging-for-photos-iphone-ipad-8738/)
[How To Turn off Geotagging in Android](https://www.ubergizmo.com/how-to/turn-off-geotagging-android/)

**Comment by brianlovin** [comment]
Solid, this is such a good point! Would you be open to add a PR creating a new file in `config/data.js` with this?
